server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nieshankun/spring-cloud-config-repo.git
          username: nieshankun
          password: NSK924841191nsk